services:
  cyclone-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: cyclone-ai-api:latest
    container_name: cyclone-ai-api
    ports:
      - "8000:8000"
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      MONGO_DB: cyclone_ai
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:8
    container_name: cyclone-ai-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
